### ISSUE TITLE
SQLite Backend

### ISSUE THREAD

**Issue by TeaWhyDee** [TeaWhyDee/SQR-Nix-Explorer#1]
Only DB interaction. Password validation etc to be performed in FastAPI.
Store names are unique.

Implement Models:
- [x] User
  - id
  - username
  - password_hash
- [x] UserStore
  - userFK
  - store_name
  - store_id (string from nix)

Implement methods:
- [x] User
    - [x] create_user - Create user with password_hash in DB
    - [x] get_password_hash:  Return password hash of user.
    - [x] get_user_list
- [x] Perform tasks with Nix stores
    - [x] Create store( user, store_name ) _store_id is also should be passed_
    - [x] Get owner of store( store_name )
    - [x] Get all stores of user( username ):  Return list of store names and their IDs
    - [x] Remove store with name

**Comment by kerniee** [comment]
в Create store( user, store_name ) должен id передаваться я думаю

**Comment by TeaWhyDee** [comment]
> в Create store( user, store_name ) должен id передаваться я думаю

да
