### ISSUE TITLE
FastAPI Auth Backend

### ISSUE THREAD

**Issue by TeaWhyDee** [TeaWhyDee/SQR-Nix-Explorer#2]
Implement FastAPI Auth Functions. 
https://fastapi.tiangolo.com/tutorial/security/first-steps/
https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/
All input and return values in JSON format.

Provide documentation for Front-End.
- [x] Add return types

Implement the following functions:
- [x] User auth
  - [x] register
    - [ ] error out if name already exists, name is illegal
  - [x] log in (get_password_hash from db and check)
    Generate JWT Token on login and return it to front-end
  - [x] log out

**Comment by kerniee** [comment]
https://github.com/TeaWhyDee/SQR-Nix-Explorer/pull/16
